# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePicture', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=12)),
                ('NationalId', models.CharField(max_length=14)),
                ('University', models.CharField(max_length=50)),
                ('Faculty', models.CharField(max_length=50)),
                ('Major', models.CharField(max_length=50)),
                ('Minor', models.CharField(max_length=50)),
                ('ExpectedGraduationYear', models.CharField(max_length=4)),
            ],
        ),
    ]
